CD adjustment

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -19,12 +19,18 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Check values
+        env:
+          AZURE_HOST: ${{ vars.AZURE_HOST }}
+          AZURE_USER: ${{ vars.AZURE_USER }}
+          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
+          AZURE_SSH_KEY: ${{ secrets.AZURE_SSH_KEY }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         run: |
-          if [ -z "${{ vars.AZURE_HOST }}" ]; then echo "AZURE_HOST variable missing"; exit 1; else echo "AZURE_HOST variable exists"; fi
-          if [ -z "${{ vars.AZURE_USER }}" ]; then echo "AZURE_USER variable missing"; exit 1; else echo "AZURE_USER variable exists"; fi
-          if [ -z "${{ secrets.AZURE_SSH_KEY }}" ]; then echo "AZURE_SSH_KEY secret missing"; exit 1; else echo "AZURE_SSH_KEY secret exists"; fi
-          if [ -z "${{ vars.DOCKER_USERNAME }}" ]; then echo "DOCKER_USERNAME variable missing"; exit 1; else echo "DOCKER_USERNAME variable exists"; fi
-          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then echo "DOCKER_PASSWORD secret missing"; exit 1; else echo "DOCKER_PASSWORD secret exists"; fi
+          if [ -z "$AZURE_HOST" ]; then echo "AZURE_HOST variable missing"; exit 1; else echo "AZURE_HOST variable exists"; fi
+          if [ -z "$AZURE_USER" ]; then echo "AZURE_USER variable missing"; exit 1; else echo "AZURE_USER variable exists"; fi
+          if [ -z "$DOCKER_USERNAME" ]; then echo "DOCKER_USERNAME variable missing"; exit 1; else echo "DOCKER_USERNAME variable exists"; fi
+          if [ -z "$AZURE_SSH_KEY" ]; then echo "AZURE_SSH_KEY secret missing"; exit 1; else echo "AZURE_SSH_KEY secret exists"; fi
+          if [ -z "$DOCKER_PASSWORD" ]; then echo "DOCKER_PASSWORD secret missing"; exit 1; else echo "DOCKER_PASSWORD secret exists"; fi
 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
